### ISSUE TITLE
Consider using the sans-IO pattern

### ISSUE THREAD

**Issue by lpil** [dinkelspiel/gleesend#1]
Hello!

This library depends on a particular HTTP client currently. This means it cannot be used on JavaScript, and it doesn't let the programmer use a HTTP client of their choice and configuration.

If instead it provided functions to construct the requests and parse the responses and left the sending to the programmer then it could be used anywhere with any configuration.

Cheers,
Louis

**Comment by dinkelspiel** [comment]
Resolved in 2.0.0
